resources:
- name: repo
  type: git
  source:
    uri: https://github.com/suizenji/webapp.git
    branch: feature/concourse

jobs:
- name: test
  plan:
  - get: repo
    trigger: true
  - task: php-unit
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: composer
      inputs: # add the get step as an input to this task
      - name: repo
      run: # read the file from the get step
        path: /bin/sh
        args:
          - -c
          - |
            cd repo/app
            composer install
            bin/phpunit --coverage-text --coverage-clover=coverage.clover
