resources:
- name: repo
  type: git
  source:
    uri: https://github.com/suizenji/webapp.git
    branch: main

# https://concourse-ci.org/php-example.html
jobs:
- name: test
  plan:
  - get: repo
    trigger: true
  - task: php-unit
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: composer
      inputs: # add the get step as an input to this task
      - name: repo
      run: # read the file from the get step
        path: /bin/sh
        args:
          - -c
          - |
            cd repo/app
            composer install
            bin/phpunit --coverage-text --coverage-clover=coverage.clover

# https://qiita.com/Esfahan/items/81eb53686506ab6bd898
- name: hello
  plan:
  - get: repo
    passed: [test]
    trigger: true
  - task: world
    file: repo/ci/task-hello.yml

# https://concourse-ci.org/manual-trigger-example.html
- name: triggered-second
  public: true
  plan:
    - get: repo
      passed: [test]
      trigger: true
    - task: simple-task
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: busybox }
        run:
          path: echo
          args: ["Hello, world!"]
