doctrine:
    dbal:
# urlが定義される場合、これが優先される。
# （Oracleだけ？）db:createするとDB名でユーザ作成するが、schema:create時は定義値userが使われる。
# db:createで作成するユーザは「XE」じゃないとコケる
# ./bin/console doctrine:database:drop --force --env=db
# ./bin/console doctrine:database:create --env=db
# ./bin/console doctrine:schema:create
        url: '%env(DATABASE_URL)%'
        driver: oci8
        dbname: XE
        host: localhost
        port: 1521
        user: XE
        password: symfony
        servicename: XEPDB1
        service: true
        charset: UTF8

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
